call p_inserir_venda('20230929', 20, 100);

SELECT A.NUMERO, COUNT(*) AS NUMERO_ITENS, SUM(B.QUANTIDADE * B.PRECO) AS FATURADO
FROM notas_fiscais A INNER JOIN itens_notas_fiscais B
ON A.NUMERO = B.NUMERO WHERE A.DATA_VENDA = '20230929'
GROUP BY A.NUMERO;