CREATE TABLE `produtos2` (
  `CODIGO` varchar(10) NOT NULL,
  `DESCRITOR` varchar(100) DEFAULT NULL,
  `SABOR` varchar(50) DEFAULT NULL,
  `TAMANHO` varchar(50) DEFAULT NULL,
  `EMBALAGEM` varchar(50) DEFAULT NULL,
  `PRECO_LISTA` float DEFAULT NULL,
  PRIMARY KEY (`CODIGO`));

SELECT * FROM produtos2;

INSERT INTO produtos2
SELECT * FROM produtos;

UPDATE produtos2 SET PRECO_LISTA = 8;

DELETE FROM produtos2;