
SELECT * FROM vendedores;

SELECT * FROM sucos_vendas.TABELA_DE_VENDEDORES;

SELECT * FROM vendedores A INNER JOIN sucos_vendas.TABELA_DE_VENDEDORES B
ON A.MATRICULA = SUBSTRING(B.MATRICULA,3,3);

UPDATE vendedores A INNER JOIN sucos_vendas.TABELA_DE_VENDEDORES B
ON A.MATRICULA = SUBSTRING(B.MATRICULA,3,3)
SET A.FERIAS = B.DE_FERIAS;ss