
CREATE TABLE TAB_IDENTITY (ID INT AUTO_INCREMENT, DESCRITOR VARCHAR(20), PRIMARY KEY(ID));

INSERT INTO tab_identity (DESCRITOR) VALUES ('CLIENTE1');

SELECT * FROM tab_identity;

INSERT INTO tab_identity (DESCRITOR) VALUES ('CLIENTE2');
INSERT INTO tab_identity (DESCRITOR) VALUES ('CLIENTE3');
INSERT INTO tab_identity (ID, DESCRITOR) VALUES (NULL, 'CLIENTE4');

DELETE FROM tab_identity WHERE ID = 2;

INSERT INTO tab_identity (ID, DESCRITOR) VALUES (NULL, 'CLIENTE5');

DELETE FROM tab_identity WHERE ID = 5;

INSERT INTO tab_identity (ID, DESCRITOR) VALUES (NULL, 'CLIENTE6');

INSERT INTO tab_identity (ID, DESCRITOR) VALUES (100, 'CLIENTE5');

INSERT INTO tab_identity (DESCRITOR) VALUES ('CLIENTE7');